site_name: " "
# Copyright
copyright: "Copyright &copy; Unacores Solutions Pvt Ltd."

extra_css:
  - css/custom.css
  
theme:
  name: "material"
  features:
    - navigation.footer
  logo: "images/unaport_logo.svg"
  palette:
    primary: "white"
    accent: "blue"
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.mark
extra:
  generator: true
  toc: false
  
# Page tree
nav:
  - "ğŸ   Overview": index.md
  - "ğŸ“ API Documentation": fiu.md
  - "ğŸ“ SDK Documentation": fiu_sdk.md
  - "ğŸ“ Self-Service Onboarding" : fiu_onboarding.md
    

      


  



