site_name: Unaport.ai - API Documentation
site_description: "Unaport.ai provides a suite of APIs designed for seamless integration in financial services, enabling account aggregation, consent management, and data sharing. Our comprehensive API documentation guides developers through the features, authentication, and best practices for utilizing our platform to build secure and scalable financial applications."

# Copyright
copyright: "Copyright &copy; Unacores Solutions Pvt Ltd."

extra_css:
  - css/custom.css
  - https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap

theme:
  name: "material"
  favicon: 'images/unaport_u.ico'
  features:
    - navigation.footer
  logo: "images/unaport_logo.svg"
  palette:
    primary: "white"
    accent: "blue"
    
  font:
    text: "Roboto"
    code: "Roboto Mono"
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
extra:
  generator: true
  toc: false
 

nav:
  - "ğŸ  Overview": index.md
  - "ğŸ’¼ FIU Onboarding": fiu_onboarding.md
  - "ğŸ“š API Documentation":
      - "ğŸ”‘ Postman Collection": fiu#postman
      - "ğŸ“ Introduction": fiu#introduction
      - "ğŸ”’ Authentication API": fiu#login
      - "ğŸ“‘ Consents API": fiu#consents
      - "ğŸ“Š Data API": fiu#data
      - "ğŸ“ˆ Analytics API": fiu#analytics
      - "ğŸ”” Notification API":
          - "ğŸ“ Consent": fiu#consent-notification-api
          - "ğŸ“Š Data": fiu#data-notification-api
          - "ğŸ“ˆ Analytics": fiu#analytics-notification-api
  - "ğŸ›  SDK Documentation": fiu_web_sdk.md
  - "ğŸ“œ Consent Relationship": fiu#consent-overview



